### ISSUE TITLE
2 port CAN bridge stopped working, what to check?

### ISSUE THREAD

**Issue by marcexec** [dalathegreat/Nissan-LEAF-Battery-Upgrade#19]
Just got the report (family car, but I'm not the main driver) that regen is reduced with single circles.
Checked in the car and the other features aren't working any more, either, like 83/92/99% battery etc.
The CAN bridge was working fine for a year now. Checked with multimeter, it's getting 14V.
Does it have LEDs? I couldn't see any.
No DTCs on LeafSpy Pro.

**Comment by dalathegreat** [comment]
This open source variant removed all extra features. They were buggy and caused me heavy support need every week.

Regen is now entirely based on what battery says. Old buggy software forced higher regen than what battery wanted. Now the software passes along the battery value unmodified to VCM, so you will see lower levels of regen when battery is full OR when it is cold.

No DTCs on Leafspy pro means the update was succesful! This software only focuses on perfecting the Battery upgrade, and making it as safe and OEM as possible. Closing this issue (since it is not an issue)
